import { AstreDescription } from "src/astres/types";

export const smallSolarSystem: AstreDescription[] = [
  {
    name: "Sun",
    type: "sun",
    width: 4,
    distance: 35,
    startAngle: 0,
    rotateSpeed: 1,
    color: "rgb(255,180,40)",
  },
  {
    name: "Mercure",
    type: "planet",
    width: 0.4,
    distance: 6,
    rotateSpeed: 5,
    color: "rgb(180, 144, 88)",
    origin: "Sun",
  },
  {
    name: "Earth",
    type: "planet",
    width: 1.2,
    distance: 12,
    rotateSpeed: 3,
    color: "rgb(19,102,150)",
    origin: "Sun",
  },
  {
    name: "Moon",
    type: "planet",
    width: 0.3,
    distance: 4,
    rotateSpeed: 3.4,
    color: "rgb(200, 200, 200)",
    origin: "Earth",
  },
  {
    name: "Mars",
    type: "planet",
    width: 0.8,
    distance: 16,
    rotateSpeed: 2,
    color: "rgb(233, 88, 26)",
    origin: "Sun",
  },
  {
    name: "Jupiter",
    type: "planet",
    width: 1.8,
    distance: 22,
    rotateSpeed: 1.4,
    color: "rgb(169, 109, 45)",
    origin: "Sun",
  },
  {
    name: "Saturne",
    type: "planet",
    width: 1.5,
    distance: 30,
    rotateSpeed: 1.1,
    color: "rgb(164,127,84)",
    origin: "Sun",
  },
  {
    name: "Uranus",
    type: "planet",
    width: 0.8,
    distance: 32,
    rotateSpeed: 1,
    color: "rgb(84,149,164)",
    origin: "Sun",
  },
  {
    name: "Netpune",
    type: "planet",
    width: 0.6,
    distance: 34,
    rotateSpeed: 0.9,
    color: "rgb(36,82,154)",
    origin: "Sun",
  },
];
